server:
  port: 8080
  servlet:
    context-path: /

pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    url:  jdbc:p6spy:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username:  root
    password:  1105lwc
    type: com.zaxxer.hikari.HikariDataSource
  output:
    ansi:
      enabled: always