package com.g7go.pagehelperdemo.demo.dao;

import com.g7go.pagehelperdemo.demo.domain.Persons;
import com.g7go.pagehelperdemo.demo.domain.PersonsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PersonsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated
     */
    long countByExample(PersonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated
     */
    int deleteByExample(PersonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated
     */
    int insert(Persons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated
     */
    int insertSelective(Persons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Persons selectOneByExample(PersonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Persons selectOneByExampleSelective(@Param("example") PersonsExample example, @Param("selective") Persons.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Persons> selectByExampleSelective(@Param("example") PersonsExample example, @Param("selective") Persons.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated
     */
    List<Persons> selectByExample(PersonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Persons record, @Param("example") PersonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Persons record, @Param("example") PersonsExample example);

    /**
     * 分页查询（自己写的）
     *
     * @param persons
     * @param pageNum
     * @param pageSize
     * @return
     */
    List<Persons> selectByPageNumSize(@Param("persons") Persons persons, @Param("pageNum") int pageNum, @Param("pageSize") int pageSize);

    List<Persons> selectByPageNumSize2(@Param("persons") Persons persons);


}